services:
  react:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run prod -- --host --port 5173"
